package io.rspndr.interview.service;

import io.rspndr.interview.model.entity.Assignment;
import io.rspndr.interview.model.entity.QAssignment;
import io.rspndr.interview.model.service.AssignmentService;
import io.rspndr.interview.repository.AssignmentRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.UUID;

@Service
@RequiredArgsConstructor
public class DefaultAssignmentService implements AssignmentService {

    private final AssignmentRepository assignmentRepository;

    @Override
    public Assignment create(Assignment assignment) {
        assignment.setId(null); // ensure id is generated by the database

        return assignmentRepository.save(assignment);
    }

    @Override
    public Assignment getById(UUID id) {
        return assignmentRepository.findById(id)
                .orElseThrow(() -> new RuntimeException("Assignment not found"));
    }

    @Override
    public void deleteById(UUID id) {
        var assignment$ = QAssignment.assignment;

        var result = assignmentRepository.update(query -> query
                .set(assignment$.deleted, true)
                .where(assignment$.id.eq(id))
                .execute());

        if (result == 0) {
            throw new RuntimeException("Assignment not found");
        }
    }

    @Override
    public List<Assignment> getByCompanyCode(String companyCode) {
        return assignmentRepository.findAllByCompanyCodeAndDeletedIsFalse(companyCode);
    }


}
