package io.rspndr.interview.service;

import io.rspndr.interview.model.entity.User;
import io.rspndr.interview.model.service.UserService;
import io.rspndr.interview.repository.UserRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.UUID;

@Service
@RequiredArgsConstructor
public class DefaultUserService implements UserService {

    private final UserRepository userRepository;

    @Override
    public User create(User user) {
        user.setId(null); // ensure id is generated by the database

        return userRepository.save(user);
    }

    @Override
    public User getById(UUID id) {
        return userRepository.findById(id)
                .orElseThrow(() -> new RuntimeException("User not found"));
    }

    @Override
    public void deleteById(UUID id) {

        if (userRepository.existsById(id)) {
            userRepository.deleteById(id);
        } else {
            throw new RuntimeException("User not found");
        }
    }

    @Override
    public List<User> getByCompanyCode(String companyCode) {
        return userRepository.findAllByCompanyCode(companyCode);
    }


}
